---
- name: Installing and Configuring Nginx on OpenSUSE Leap 15.6
  hosts: websrv
  become: yes
  vars_files:
    - vars/main.yml

  tasks:
    # 1. Installing the repository and Nginx
    - name: Adding the Nginx repository GPG key
      rpm_key:
        state: present
        key: "https://nginx.org/keys/nginx_signing.key"

    - name: Adding the official Nginx repository
      command: zypper --non-interactive addrepo -G -f -K https://nginx.org/packages/sles/15 nginx
      register: add_repo
      changed_when: "'successfully added' in add_repo.stdout"
      ignore_errors: yes

    - name: Install Nginx
      zypper:
        name: nginx
        state: present
        disable_gpg_check: yes
        update_cache: yes

    # 2. Setting up Nginx
    - name: Creating a web server root directory
      file:
        path: "{{ nginx_web_root }}"
        state: directory
        owner: "{{ nginx_user }}"
        group: "{{ nginx_group }}"
        mode: '0755'

    - name: Deploy index.html with server IP
      template:
        src: templates/index.html.j2
        dest: "{{ nginx_web_root }}/index.html"
        owner: "{{ nginx_user }}"
        group: "{{ nginx_group }}"
        mode: '0644'

    - name: Setting up the main Nginx config
      blockinfile:
        path: /etc/nginx/nginx.conf
        block: |
          server {
              listen 80;
              server_name _;
              root {{ nginx_web_root }};
              index index.html;

              location / {
                  try_files $uri $uri/ =404;
              }
          }
        marker: "# {mark} ANSIBLE MANAGED BLOCK - NGINX SERVER CONFIG"
        insertafter: 'http {'

    - name: Checking Nginx configuration
      command: nginx -t
      register: nginx_config_test
      changed_when: false

    # 3. Setting up firewalld
    - name: Allow HTTP in firewalld
      firewalld:
        service: http
        state: enabled
        permanent: yes
        immediate: yes

    # 4. Starting the service
    - name: Starting and Enabling Nginx
      service:
        name: nginx
        state: started
        enabled: yes

    # 5. Checking work
    - name: Checking Nginx operation
      uri:
        url: "http://localhost"
        return_content: yes
      register: nginx_test
      until: nginx_test.status == 200
      retries: 5
      delay: 3
      ignore_errors: yes

    - name: Output of the test result
      debug:
        msg: "Nginx is working correctly. Available at http://{{ ansible_default_ipv4.address }}"
      when: nginx_test.status == 200
